### ISSUE TITLE
implement EMC-309 client-side before EMC does

### ISSUE THREAD

**Issue by wafflecoffee** [WitherDoggie/chat-control#14]
https://track.emc.gs/issue/EMC-309  
Dunno how you could do this but maybe some sort of Regex to match which chat channel a message is in, e.g.:  
`C\-\d|M\-\d|Sup\-\d|L|R|G` to match the channel  
`\s\•?\s?\★?\s?\D+\:` to filter playername, staff/friend symbols, colon  
and make everything after the colon a certain colour depending on mod menu settings  

Might be out of the scope of this project, but might as well make it somewhat comprehensive  
Could even port some of the chat features from the [5zig Mod](https://github.com/5zig-reborn/The-5zig-Mod) if you're ambitious enough

**Comment by WitherDoggie** [comment]
This is potentially do-able. Will look into it after work today.

Anything past this is just notes for me.

Easiest way would be to modify message before it is ever shown to the client. This will be complicated because of how the game stores chat messages. May have to re-write the way chat messages are handled because they are not stored as strings.

**Comment by WitherDoggie** [comment]
After reading through some stuff and looking at how the client receives messages, this is possible. Will take some time to implement. May be a week before it is finished.

**Comment by WitherDoggie** [comment]
I spent several hours today attempting to implement this. I can filter the messages, but every attempt I made at coloring the chat either crashed the game or just did nothing. If you know of any open source mods that do chat coloring, link them to me please so I can study them and see what exactly I need to hook into to to modify chat message colors.

**Comment by WitherDoggie** [comment]
Client is able to detect channels and apply a color based on the channel. Needs to ignore the username, friend dot, and staff star. Also need config options. Could potentially ignore /resshout messages since they are consistent in color. Ignoring colored staff messages theoretically is possible, but I still need to mess around with a solution.

**Comment by WitherDoggie** [comment]
Sadly I will have to close this. I have no way of testing this feature on EMC. Obviously, I don't want it to accidentally break a rule and myself be punished. I apologize for getting your hopes up that I may be able to do this.
